FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install -g @angular/cli@17 && npm install
COPY . .
RUN ng build --configuration production

FROM nginx:alpine
COPY --from=build /app/dist/frontend /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
