CREATE TABLE IF NOT EXISTS raw_responses (
    id SERIAL PRIMARY KEY,
    response_id VARCHAR(255) UNIQUE,
    form_type VARCHAR(20),
    employee_id VARCHAR(50),
    sede VARCHAR(50),
    cargo VARCHAR(100),
    age_range VARCHAR(20),
    tenure_months INT,
    tipo_desligamento VARCHAR(50),
    faltas_6m INT,
    satisfacao_q1 INT, satisfacao_q2 INT, satisfacao_q3 INT, satisfacao_q4 INT, satisfacao_q5 INT,
    recompensa_q6 INT, recompensa_q7 INT, recompensa_q8 INT, recompensa_q9 INT, recompensa_q10 INT,
    gestor_q11 INT, gestor_q12 INT, gestor_q13 INT, gestor_q14 INT, gestor_q15 INT,
    wlb_q16 INT, wlb_q17 INT, wlb_q18 INT, wlb_q19 INT, wlb_q20 INT,
    ambiente_q21 INT, ambiente_q22 INT, ambiente_q23 INT, ambiente_q24 INT, ambiente_q25 INT,
    open_response_1 TEXT, open_response_2 TEXT, open_response_3 TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_quality_flag VARCHAR(50),
    data_quality_notes TEXT
);

CREATE TABLE IF NOT EXISTS processed_features (
    id SERIAL PRIMARY KEY,
    response_id VARCHAR(255) UNIQUE,
    satisfacao_media FLOAT,
    satisfacao_std FLOAT,
    recompensa_media FLOAT,
    recompensa_std FLOAT,
    gestor_media FLOAT,
    gestor_std FLOAT,
    wlb_media FLOAT,
    wlb_std FLOAT,
    ambiente_media FLOAT,
    ambiente_std FLOAT,
    satisfacao_geral_media FLOAT,
    satisfacao_geral_std FLOAT,
    red_flag_count INT,
    yellow_flag_count INT,
    interaction_gestor_recompensa FLOAT,
    interaction_wlb_satisfacao FLOAT,
    faltas_normalized INT,
    cargo_encoded INT,
    age_encoded INT,
    tenure_normalized FLOAT,
    target INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS model_predictions (
    id SERIAL PRIMARY KEY,
    employee_id VARCHAR(50),
    prediction_date TIMESTAMP,
    risk_score FLOAT,
    risk_level VARCHAR(20),
    top_driver_1 VARCHAR(100), shap_value_1 FLOAT,
    top_driver_2 VARCHAR(100), shap_value_2 FLOAT,
    top_driver_3 VARCHAR(100), shap_value_3 FLOAT,
    suggested_actions TEXT,
    intervention_status VARCHAR(20),
    intervention_date TIMESTAMP,
    intervention_outcome VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
